apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
     metadata:
       labels:
         app: demo
         env: dev
     spec:
       containers:
       - name: demo
         image: nginx:latest
